### ISSUE TITLE
How ldcast predict 20 time steps from 4 time steps input?

### ISSUE THREAD

**Issue by jacksd233** [MeteoSwiss/ldcast#11]
Hello
I successfully run the demo code and find that the model can predict 20 time steps from 4 time steps input. But I am a little confused about how this happens.

In your article 4.2.1 Forecaster, you said that"we train the model to predict Dout = 5 encoded output time steps simultaneously from Din = 1 encoded input time steps". In my understanding, this means you can use state at time t to predict t+1, t+2, t+3, t+4 and t+5. Now you have state at t-3, t-2, t-1 and t, why the model can predict t+1 ~ t+20?

Hope I have made my question clear.

**Comment by jleinonen** [comment]
Sorry, I forgot to answer to this one - in the forecaster component of LDCast there is a cross-attention transformer layer that operates on the temporal dimension. That transforms from the 4 time step input coordinates to the 20 time step output coordinates. See the paper for details.
