### ISSUE TITLE
UnboundLocalError: local variable 'R_pred' referenced before assignment and Out-of-Memory Error

### ISSUE THREAD

**Issue by nathzi1505** [MeteoSwiss/ldcast#2]
Hi!
Thanks for the great work.
I have been playing around with the demo (1 ensemble) and I got an error at this line. 
https://github.com/MeteoSwiss/ldcast/blob/a6b2bd97b17190e86d116761a8513953ededb492/scripts/forecast_demo.py#L114

Also, with an ``--ensemble-members=2`` the code seems stuck after the PLMS sampler step as the processes do not seem to join ... any reason why?

**Comment by jleinonen** [comment]
Sorry for the inconvenience, the 1 ensemble member option was broken in the last update, I fixed it in 820a6ca.

The version with multiple ensemble members works fine on my machine. Do you get the output written to files or does it hang before that? Could you say a little about your setup (e.g. CPU or GPU)?

**Comment by nathzi1505** [comment]
Thanks @jleinonen for the quick fix.
I am using an RTX 2080Ti (11 GB VRAM) for inference. It looks like I am going Out-Of-Memory.
What was your GPU setup when you did the training?
