### ISSUE TITLE
Diffusion initialization 

### ISSUE THREAD

**Issue by byphilipp** [MeteoSwiss/ldcast#8]
Hello
Thank you for code and model sharing

I think the random image sampling is not best in the nowcasting problem.
The good idea is doing the image initialization (see x_T argument in models/diffusion/plms.py) based on short range NWP forecast.
Are you tested this approach ?

**Comment by jleinonen** [comment]
Interesting idea. This could be possible but I'm not sure - I think the diffusion process needs to start from random noise for the mathematics to work. But maybe there is a way to incorporate this.

**Comment by jleinonen** [comment]
Closing this as there is not really a concrete action to take here. Also, the experiments in this paper https://arxiv.org/abs/2305.03486 suggest that this approach would not work.
